### ISSUE TITLE
Running Morpheus on a 32 Bit Windows

### ISSUE THREAD

**Issue by somakray** [cwenger/Morpheus#2]
I'm trying to run Morpheus on a 32 Bit Windows 7 SP1 and get the following errors. Is it a 32 Bit issue? Can Morpheus be run on a Win32 system?

Thanks

```
Initializing...
Starting C:\MorpheusPostAcquisitionSearch\UF_Top15_QEPlus_Test.RAW...
Extracting and preprocessing MS/MS spectra...
System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {1D23188D-53FE-4C25-B032-DC70ACDBDC02} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Morpheus.TandemMassSpectra.Load(String rawFilepath, Int32 minimumAssumedPrecursorChargeState, Int32 maximumAssumedPrecursorChargeState, Double absoluteThreshold, Double relativeThresholdPercent, Int32 maximumNumberOfPeaks, Boolean assignChargeStates, Int32 maximumThreads)
   at Morpheus.TandemMassSpectra.Load(String rawFilepath, Int32 minimumAssumedPrecursorChargeState, Int32 maximumAssumedPrecursorChargeState, Double absoluteThreshold, Double relativeThresholdPercent, Int32 maximumNumberOfPeaks, Boolean assignChargeStates, Boolean deisotope, MassTolerance isotopicMZTolerance, Int32 maximumThreads)
   at Morpheus.DatabaseSearcher.DoSearch()
Finished!
```

**Comment by cwenger** [comment]
Hi somakray,

Morpheus works on 32-bit Windows. It sounds like you just need to install [Thermo MSFileReader](https://thermo.flexnetoperations.com/control/thmo/search?query=MSFileReader).

-Craig
